services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: crm_admefi
      MYSQL_USER: admefi
      MYSQL_PASSWORD: admefi123
    ports:
      - 3307:3306
    volumes:
      - crm_mysql_data:/var/lib/mysql
volumes:
  crm_mysql_data: